- templates/accompany-posting.html
- templates/accompany.html
- templates/backoffice-main.html
- templates/exhibition-detail.html
- templates/exhibition-posting.html
- templates/my-page.html
- templates/review-posting.html
- templates/review.html
- templates/signin.html
- templates/signup.html
- templates/updated-user.html
> :lipstick:Design: navbar 부트스트랩 css 추가

- static/js/signin.js
- templates/signin.html
> :sparkles:Feat: 일반 로그인 기능 구현 #10

- index.html
- static/js/index.js
index.js 파일에서 좋아요 기능의 알러트를 삭제했습니다.
index.html 파일에서 좋아요의 개수를 표시하는 span 태그의
class 선택자명이 heat-num 으로 되어있어 heart-num으로 교체했습니다.
> :hammer:Refact:메인페이지 수정 #1 #3

- index.html
- static/css/backoffice-main.css
- templates/backoffice-main.html
관리자 메인화면 부분입니다.
index.html의 전시카드 하단 여백 50px도 추가해서 함께 보냅니다.
> :sparkles:Feat:backoffice-main 화면구현 완료 #5 #6

- static/js/api.js
- static/js/index.js
[필요]
현재 전시회 정보 불러왔을 때 부터 좋아요를 누른 경우 반영 불가
> :spakles:Feat:메인 페이지 좋아요 구현 #3

- static/css/signup.css
- templates/signup.html
회원가입 화면 구현이 완료되었습니다.
회원가입을 위한 여러 정보 입력칸 중
필수적으로 입력해야하는 부분은
유저에게 ** 표시를 남겨주어 알렸고,
동시에 태그에 required 속성을 주었습니다.
프로필 이미지 받는 기능은 input 태그 중 type=file 속성을 주어서
구현했는데, 유저가 업로드 할 수 있는 파일 확장자를
jpg, jpeg, png, gif, bmp로 제한하였습니다.
또한 capture='camera' 속성을 주어 모바일 접속자들이 카메라를 켤 수 있게
하였습니다.
> :sparkles:Feat:회원가입 화면 구현 완료 #11 #12

- static/css/updated-user.css
- templates/updated-user.html
회원정보 수정 부분 화면구현이 완료되었습니다.
로그인, 회원가입과 달리
화면구현작업이 api 연결하는 js 작업보다 선행되었으므로
id 선택자가 원하는 이름대로 되었는지 한번 더 체크해주세요.
id 선택자를 활용한 일이 없으니 api js 작업에 맞게 고쳐 쓰시면 됩니다.
> :sparkles:Feat:회원정보수정 화면구현 완료 #14 #15

- static/css/my-page.css
- templates/my-page.html
마이페이지 화면 구현이 완료되었습니다.
상단에 유저 정보 관련 내용,
하단에 해당 유저가 좋아요한 전시 목록이
배치되어 있습니다.
회원수정 버튼과 회원탈퇴 버튼도
이 페이지 내에 배치되어 있습니다.
> :sparkles:Feat:마이페이지 화면 구현 완료 #17 #18

- static/js/index.js
- static/js/signin.js
index.js에 있던 setLocalStorage 함수와 소셜로그인 시 url에서 access 토큰 얻는 코드 signin.js로 옮겼습니다.
> :art:Style: 로그인 관련 함수 signin.js로 이동 #10

- index.html
- static/css/exhibition-detail.css
- templates/exhibition-detail.html
전시상세 부분 화면구현 완료했습니다.
하트 부분 js는 어떻게 건드려야될 지 모르겠어서
그냥 껍데기만 만들었습니다.
세만님께 맡깁니다
[그외]
index.html에 하트 개수 표시하는 heart-num 부분 클래스가
저번에 수정했는데도 heat-num 으로 표현되어 있네요.
다시 수정해서 보냅니다.
> :sparkles:Feat:전시상세 부분 화면구현 완료 #20 #21

- static/js/index.js
메인페이지 입장 시, 사용자의 좋아요 유무에 따라 좋아요를 눌렀다면 빨간하트,
누르지 않았다면 빈하트가 보이게 수정하였습니다.
> :sparkles:Feat: 전시회 유저별 좋아요 하트색 세팅 #3

- static/css/exhibition-posting.css
- templates/exhibition-posting.html
전시 수동 등록화면 구현이 완료되었습니다.
최상단에 전시회 선택 옵션은 혹시 몰라서 만들어 두었습니다.
AI로 데려올 카테고리 등을 넣으면 될 것 같습니다.
필요 없으면 삭제해도 됩니다.
> :sparkles:Feat:전시 수동 등록 화면 구현 완료 #23 #24

- static/js/api.js
- static/js/updated-user.js
- templates/updated-user.html
이미지 수정 제외 프로필 수정기능 구현
[필요]
프로필 이미지 존재시 이미지 수정
> :sparkles:Feat: 프로필 수정 기본 구현 #19

- static/css/review-posting.css
- static/js/review-posting.js
- templates/review-posting.html
리뷰 작성 화면 구현 완료되었습니다.
별 누르면 왼쪽 별부터 누른 별까지 채운 별로 변하는
코드를 review.posting.js 파일에 넣어두었습니다.
> :sparkles:Feat:리뷰작성 화면 구현 완료 #26 #27 #28

- static/js/signin.js
setLocalStorage가 불가능한 상황에서 error 발생
그 이후 else 처리 불가능 했던 부분 수정
> :bug:Fix: 로그인 실패시 처리 수정 close #10

- static/css/accompany.css
- templates/accompany.html
동행글 보기 화면 구현 완료되었습니다.
브라우저 상에서 보이는
회색 박스 단위로 1개의 동행글 개념이 성립합니다.
동행글 A 에 대한 신청댓글 A-1, A-2, A-3 ... ...은
모두 같은 회색 박스 안에 위치하게 되며,
동행글 B 는 A 패밀리 아래에서
독자적인 회색박스를 가지고 새롭게 생성되는 형태입니다.
구성하려니까 많이 복잡하네요.
js 로직도 복잡할 것 같아요.
화이팅!
> :sparkles:Feat:동행글 보기 화면 구현 완료 #32 #33

- index.html
- static/js/api.js
- static/js/index.js
> :sparkles:Feat: 페이지네이션 기본 구현 #3

- index.html
- static/js/my-page.js
- static/js/signup.js
- static/js/updated-user.js
if문으로 처리하던 분기대신 논리연산자 ||로
기본값 '' 지정
> :art:Style: formData 입력 방식 변경 #13 #19

- static/js/exhibition-detail.js
- templates/exhibition-detail.html
1. 화면에서 이미지, 좋아요, 제목, 장소, 기간, 내용 데이터를 확인할 수 있습니다.
2. 예약하기 버튼을 추가하여 상세 페이지에서도 예약 페이지로 이동할 수 있습니다.
3. 내용 부분 보기 좋게 만들고 싶으나 아직 방법을 모르겠습니다.
4. 다음 PR은 리뷰 보기 또는 동행글 보기 구현입니다.
> :sparkles:Feat: 전시 상세페이지 기본 기능 #20 #22

- index.html
- static/css/index.css
- static/css/navbar.css
- templates/navbar.html
네비게이션바의 로고 및 타이틀 크기와
우측 버튼들 정렬방식을 바꾸었습니다.
관련해서 html과 css파일 모두 변경 있습니다.
또한 네비바와 연동되는 반응형 연구하면서 index.html 및 index.css도
디자인 손보았습니다.
> :art:Style:네비게이션바 디자인 살짝 수정 #38 #39

- static/css/backoffice-main.css
백오피스 부분도 이미지 알맞게 들어가도록 수정 했습니당~
> :art:Style:백오피스-메인 페이지도 이미지 수정

- static/js/api.js
- static/js/exhibition-detail.js
- templates/exhibition-detail.html
전시 상세 페이지에서 리뷰 보기 버튼 클릭 시 리뷰 카드들이 쭉 뜨게
하였으나 css에 문제가 있어 동현님이 수정해 주시기로 했습니다.
> :sparkles:Feat: 리뷰 보기 기능 구현 #29 #31

- static/js/api.js
- static/js/navbar.js
- templates/navbar.html
카테고리와 페이지 버튼 연결
```javascript
// 카테고리 id 기준으로 addEventListener 부여
for (var i = 1; i < 9; i++)
document.getElementById(i).addEventListener("click", function () {
selectCategory(this.value)
})
}
```
카테고리가 늘어났을 때 유지보수하기 쉽도록 for문 사용
> :sparkles:Feat: category 기능 연결 #40

- static/js/index.js
```
window.location.href = `${frontendBaseURL}/index.html?${page.split('?')[1]}` 
``` 
명시적으로 작성했던 url에서
```
window.location.href = `${frontendBaseURL}${window.location.pathname}?${page.split('?')[1]}`
``` 
으로 변경하며 추후 path를 변경해도 자동적으로 반영
> :art:Style:location.pathname 사용 #3

- index.html
index.html 파일에 전시회 카드 예시 부분이 있어 같이 띄워지는 에러를
발견하고 수정했습니다.
> :bug:Fix: html 파일에 전시회 카드 정리 #1

- static/css/accompany.css
- static/css/review.css
- static/css/signin.css
- static/css/signup.css
- static/js/backoffice-main.js
- templates/accompany.html
- templates/exhibition-posting.html
- templates/review.html
1.리뷰와 동행글에서 검색바 제거
2.구글 로그인 마크 크기 유지되게 조정
3.백오피스메인 화면에서 전시회 목록의 버튼 중 상세보기, 예약하기로
되어있던 부분을 수정하기, 삭제하기로 보이도록js수정 **js로직 추가 필요
4.전시 포스팅 html에 예약 url 입력 플레이스 홀더 표시내용 변경
5.회원가입 입력값들의 크기 조정 옵션 변경 및, 디자인 최적화 위한 플레이스홀더 인덴트 추가
> :art:Style:다양한 화면구현 옵션 리터칭

- static/js/index.js
- static/js/navbar.js
category의 addEvnetListner를 생성하는 for문이 if (payload)안에서 선언되어 비로그인시 카테고리 무반응 문제 해결
> :bug:Fix:비로그인 시 카테고리 이슈 #40

- index.html
- static/js/api.js
- static/js/backoffice-main.js
- static/js/index.js
- templates/backoffice-main.html
```javascript
// enter입력시 함수 실행
document.getElementById("search").addEventListener("keydown", function (e) {
if (e.code === 'Enter') {
exhibitionSearch(this)
}
})
document.getElementById("searchButton").addEventListener("click", function () {
exhibitionSearch(this)
})
```
Enter 입력 감지 event와 클릭 이벤트 부여
[필요]
검색 결과가 없는 경우 대처 방안
> :sparkles:Feat: 검색기능 연결 #3 #7

- static/js/exhibition-detail.js
- static/js/review.js
- templates/exhibition-detail.html
1. 리뷰와 관련된 함수 review.js에 옮기고 import 하는 방식으로 바꾸었습니다.
2. 리뷰 보기 클릭 시 리뷰 나타남 & 추천바 사라짐. 다시 한 번 더 누르면 리뷰 사라지고 추천바 나타남
> :bug:Fix: 함수 파일 분리 및 리뷰 보기 클릭 이벤트 수정 #29 #31

- index.html
지난 PR 때 이 부분을 삭제하였으나 코드를 직접 작성하지 않은 사람으로 하여금 js로 붙는 부분이 html로 어떻게 구성되어 있는지 파악할 수 있게 다시 살려서 주석 처리하였습니다.
> :art:Style: js로 전시회 객체 붙는 부분 주석 처리 #1

- static/js/exhibition-detail.js
스크롤바가 예약하기 버튼의 위치보다 아래로 가면 추천바가 사라집니다.
> :sparkles:Feat: 스크롤 위치에 따른 추천바 숨기기 #22

- static/css/exhibition-posting.css
- static/js/navbar.js
1. 로그인 후 네비게이션바에서 내정보와 로그아웃 사이의 간격 조절
2. 전시등록 페이지에서 이미지 업로드란의 플레이스 홀더 높이 조절
> :art:Style:간단 디자인 수정사항들

- static/js/exhibition-detail.js
1. 전시 추천바에 추천되는 전시 연결했습니다
2. 전시명이 긴 경우, 추천바가 전시명을 가리는 경우가 있어서 스크롤이 전시명 높이보다 낮아졌을 때 생기게 수정하였습니다.
> :sparkles:Feat: 전시 추천바에 추전 전시 연결 #22

- templates/exhibition-detail.html
1. js 연결을 위한 id를 추가했습니다.
2. 전시명 위치를 이미지 오른쪽에서 맨 위로 옮겼습니다.
3. 리뷰 보기 버튼을 이용 후기로 변경했습니다.
4. 동행글 보기 버튼을 동행 구해요!로 변경했습니다.
5. 리뷰 및 동행글이 붙는 부분에 해당 모양을 참고하는 html 파일을 주석으로 명시하였습니다.
6. 추천 전시바 상단 이름을 이런 전시는 어떠세요?로 변경했습니다.
7. 로딩될 때 추천 제목이라는 글자 뜨는 게 보기 좋지 않아 해당 글자를 삭제했습니다.
8. 장소, 날짜, 설명에 전시라는 단어가 반복되어 삭제했습니다.
> :sparkles:Feat: id 추가, 전시명 위치 변경, 주석 추가 등 #20

- static/css/accompany-apply-posting.css
- static/css/accompany.css
- static/css/backoffice-main.css
- static/css/exhibition-detail.css
- static/css/index.css
- static/css/my-page.css
- static/css/review.css
- static/js/accompany.js
1. 일반유저 마이페이지 모양을 좀 더 스마트하게 변경하였습니다
2. 모든 html 파일의 화면 바닥에 적절한 여백을 주는 작업 완료
3. 페이지네이션에 최신 디자인 적용
4. 동행글의 CSS 깨짐 현상 수정
5. 리뷰 및 동행글의 회색박스 컬러 좀 더 밝은 색으로 변경 #e1e1e1
6. accompany-apply-posting.css에 쓸모없는 검색바 관련 옵션 제거
> :art:Style:화면구현 디자인 보완

- static/js/navbar.js
이동 url을 pathname을 기준으로 설정하면서
프로필의 pathname을 가져오는 이슈 존재
```javascript
if (payloadParse.is_admin) {
window.location.href = `${frontendBaseURL}/templates/backoffice-main.html?category=${category}`
} else {
window.location.href = `${frontendBaseURL}/index.html?category=${category}`
}
```
url을 명시적으로 지정하며 불필요한 page 정보 삭제
> :bug:Fix: 프로필에서 카테고리 이슈 해결 #40

- static/js/review.js
> :bug:Fix: 리뷰 작성 버튼 오류 수정 #28

- static/js/backoffice-main.js
- static/js/index.js
- static/js/my-page.js
비로그인 시 좋아요 함수를 막기위한 payload확인 추가
db에 올린 이미지 불러오는 링크 연결
> :bug:Fix: 이미지 연결 이슈 수정 #3 #7 #19

- static/js/navbar.js
```javascript
function selectCategory(category) {
if (payloadParse && payloadParse.is_admin) {
window.location.href = `${frontendBaseURL}/templates/backoffice-main.html?category=${category}`
} else {
window.location.href = `${frontendBaseURL}/index.html?category=${category}`
}
}
```
메인이나 백오피스가 아닌 곳에서 클릭시 이동 위치를
파악하기 위한 조건문에 payload가 없는 경우 추가
> :bug:Fix: 비로그인 카테고리 이슈 수정 #40

- static/js/review.js
리뷰 수정하고 있는 도중에는 후기 작성하기 버튼을 누를 수 없게끔 수정했습니다.
> :sparkles:Feat: 리뷰 수정 시 후기 작성하기 버튼 비활성화 #28

- static/css/exhibition-detail.css
- static/css/review-posting.css
- static/css/review.css
1. 전시상세 페이지에서 제목이 좀 더 가운데로 모여 보일 수 있게, 보이는 좌우 여백을 조정했습니다.
2. 리뷰작성 단계에서 이미지를 업로드하는 곳의 placeholer 위치를 중앙으로 조정했습니다.
> :art:Style:화면구현 수정 추가

- static/js/api.js
> :hammer:Refact: url 수정 #4

- static/js/signin.js
> :hammer:Refact: 소셜로그인 탈퇴 후 로그인 수정 #10

- static/js/exhibition-detail.js
로그인 하지 않은 사용자는 좋아요를 누를 수 없게 막아두었습니다.
> :bug:Fix: 비로그인 시 전시 상세페이지에서 좋아요 비활성화

- static/js/review-posting.js
- static/js/review.js
1. 비로그인 시 이용후기 버튼을 한 번 눌렀다가 다시 누른 후 또 다시 누를 때 리뷰 목록이 나오지 않는 에러 해결했습니다.
2. 비로그인 상태에서 후기 작성하기 버튼 클릭 시 로그인 후 이용하라는 경고창이 뜨게끔 수정했습니다.
> :bug:Fix: 비로그인 오류 수정 #28 #31

- static/js/accompany-posting.js
- static/js/accompany.js
- static/js/apply-posting.js
1. 비로그인 시 동행구해요! 버튼을 한 번 눌렀다가 다시 누른 후 또 다시 누를 때 동행구하기 글 목록이 나오지 않는 에러 해결했습니다.
2. 비로그인 상태에서 동행신청 버튼 클릭 시 로그인 후 이용하라는 경고창이 뜨게끔 수정했습니다.
3. 비로그인 상태에서 동행 구하기 버튼 클릭 시 로그인 후 이용하라는 경고창이 뜨게끔 수정했습니다.
4. 동행글 작성한 본인은 동행신청이 아닌 답글달기 버튼으로 보입니다.
5. 동행글 작성한 본인이 답글 달 때 보라색 안내문구는 저도 갈래요! 가 아닌 이런 분을 구해요!로 뜨게끔 수정했습니다.
> :bug:Fix: 비로그인 및 기타 오류 수정 #34 #37

- static/js/backoffice-main.js
- static/js/exhibition-detail.js
- static/js/index.js
- static/js/my-page.js
API에서 제공받는 이미지 URL이 https://에 해당하는 https%3A%2F%2F
이 아닌 https:/에 해당하는 https%3A%2F으로 전달되어 자동적으로 수정하는
로컬환경이 아닌 배포환경에서 URL을 제대로 인식하지 못하였음
> :hammer:Refact: 이미지 src 이슈 해결 close #148

- static/js/exhibition-detail.js
- templates/exhibition-detail.html
1. 상세페이지에서 좋아요 기능 동작하지 않는 오류 해결
2. 시작날짜와 종료날짜가 존재하는 경우에만 시작날짜 ~ 종료날짜로 보이게 하고, 아닌 경우에는 "상시"로 뜨게끔 수정
3. 직접 업로드한 전시의 경우 상세페이지와 추천바에서 이미지가 제대로 뜨지 않는 오류 해결
4. 예약하기 url이 없는 경우 예약하기 버튼 클릭 시 알림창 뜨는 것으로 수정 (예약하기 버튼을 없애려고 했지만 해당 전시가 예약이 필요없거나 현장 예매만 가능하다는 걸 알려주는 게 좋을 것 같아 이렇게 수정했습니다. 처음에는 예약하기 버튼을 없애고 전시 상세페이지에 접속했을 때 알림창이 뜨게 하였으나 전시 정보가 로드되지 않은 상태에서 알림창이 뜨는 게 보기 좋지 않았습니다.)
> :bug:Fix: 직접 등록한 전시 및 좋아요에 대한 오류 해결 #20 #22

- static/css/backoffice-main.css
> :sparkles:Feat: 백오피스 전시 이미지 커서모양 변경 #6

- static/js/accompany.js
- static/js/apply-posting.js
동행 구하기 작성자와 동행 신청하기 작성자가 일치하는 경우 "이런 분을
구합니다!"로 나오고, 일치하지 않는 경우 "저도 같이 갈래요!" 로 나옵니다.
> :bug:Fix: 작성자에 따라 안내문구 오류 수정 #34

- static/js/signup.js
responseJson의 message에서 serializer.erros를 받아올 수 있도록 수정
> :hammer:Refact: 중복 가입 방지 메시지 수정 #13

- static/js/my-page.js
> :hammer:Refact:어드민 프로필 수정 제한 close #19

- static/js/backoffice-main.js
- static/js/index.js
- static/js/my-page.js
> :hammer:Refact: 전시회 기간 수정

- static/js/signin.js
로그인 실패시 status 반환에서 responseJson에 기반한 메시지 반환
> :hammer:Refact: 로그인 실패 시 alert창 수정

- static/js/navbar.js
로그인 시 nav-item을 가지고 있는 li가 생성되지 않아 css가 망가지는 이슈
해결
> :art:Style: 로그인 시 nav-item 추가 #39 #40

- static/css/index.css
- static/js/index.js
사진 클릭 시 상세페이지로 이동
사진에 마우스 올렸을 때 선택 모양으로 커서 바뀜
> :sparkles:Feat: 메인페이지 이미지 클릭 시 상세페이지로 이동 기능 추가 #2 #3

- static/js/backoffice-main.js
- static/js/index.js
사용자에게 기능이 있음을 암시하기 위한 커서 효과 추가
> :art:Style: 검색 돋보기 커서효과 추가

- static/js/signin.js
- templates/my-page.html
```javascript
// normal login
window.history.go(-1)
// google login
window.history.go(-3)
```
widnow.history.back == widow.history.go(-1)
구글 로그인 이동 페이지 개수 계산 후 조정
> :hammer: 로그인 후 이동 페이지 개선

- static/js/navbar.js
my-page에서 로그아웃시 메인페이지로 이동하는 함수 문제 해결
> :bug: 로그아웃 오류 수정

- static/js/signin.js
로그인 확인 -> 일반 로그인 -> 구글 로그인 순으로 함수 위치를
변경했습니다.
> :art:Style: 함수 위치 변경

- static/js/backoffice-main.js
- static/js/index.js
- templates/popup.html
업데이트 사항 및 리뷰/동행글 개수
메인페이지와 백오피스 메인페이지 둘 다 추가했습니다.
> :sparkles:Feat: 메인페이지 리뷰/동행글 개수 및 업데이트사항 추가 #3 #7

- static/js/exhibition-detail.js
처음 상세게시글 입장 시 추천바 안 보임
스크롤 내렸다가 쭉 올리면 추천바 보임
이용후기 버튼 기준으로  스크롤에 따라 추천바가 보이고 안 보임
> :sparkles:Feat: 추천바 사라지는 기준 수정 #22

- static/js/review-posting.js
- static/js/review.js
리뷰가 하나도 없을 때 리뷰가 없음을 알리는 문구 추가했습니다.
> :sparkles:Feat: 리뷰 없을 때 기본 문구 출력 #31

- index.html
- static/css/backoffice-main.css
- static/css/index.css
- templates/backoffice-main.html
1. 메인페이지 index.html의 검색바에 플레이스 홀더를 추가했습니다. "원하는 전시를 키워드로 검색해보세요"
2. 백오피스 메인페이지 backoffice-main.html의 검색바에 플레이스 홀더를 추가했습니다. "찾고자 하는 전시를 키워드로 검색해보세요."
각각 css 파일에 text-indent 옵션을 추가했습니다.
> :art:Style:검색바에 플레이스홀더 추가

- templates/navbar.html
> :art:Style: 비로그인 카테고리 위치 조정

- static/js/api.js
- static/js/index.js
> :sparkles:Feat: 전시 인기랭킹 API 추가 #3 #4

- index.html
- static/css/index.css
> :sparkles:Feat:인기전시 화면구현 완료

- static/js/api.js
> :bug:Fix: 동행 수락 API 닫는 중괄호 추가

- index.html
- static/css/index.css
- static/js/index.js
1. 인기 전시 클릭 시 새창으로 열리지 않고 해당 페이지에서 바로 이동하게끔 수정함
2. 이미지 들어가니까 하트 opacity 0.5로 되어 있어서 잘 안 보임 -> opacity 제거
3. 백엔드에서 인기 전시 데이터 받아서 화면에 알맞게 넣음
> :sparkles:Feat: 인기 전시 구현 완료 #1 #2 #3

- static/css/my-page.css
원래 이미지 너비에 따라 움직이던 이미지 박스 너비를 일정 크기로
고정시켰습니다.
> :sparkles:Feat: 프로필 이미지 박스 고정 #18

- static/js/accompany-editing.js
- static/js/accompany-posting.js
- static/js/accompany.js
목표인원 id값이 고유한 값이 아니어서 데이터 반영이 제대로 되지 않는 것을
확인하고 수정했습니다.
> :bug:Fix: 동행 채택 기능 목표인원 id값에 의한 오류 해결 #200

- static/js/accompany-posting.js
- static/js/accompany.js
- static/js/apply-posting.js
동행 구하기 /신청하기 글 작성했을 때 생기는 부분에 닉네임 클릭 시
마이페이지로 이동이 안 되고 있어서 수정했습니다.
> :bug:Fix: 동행 구하기/신청하기 닉네임 클릭 시 마이페이지로 이동 #34

- static/js/signin.js
로컬 환경과 다르게 배포환경에서 go함수가 제대로 적용이
되지않아 로그인 직후의 페이지에서 페이로드가 제대로 적용 안되는 이슈
발생
```javascript
window.location.href = document.referrer
```
일반 로그인은 해결했으나
구글 로그인은 적용 미확인
> :bug:Fix: 배포환경 로그인 에러
